from __future__ import annotations

import json
import os
import re
from datetime import datetime
from pathlib import Path
from typing import Any
import hashlib

from ..config import DATA_DIR, IMG_EXTS, MEDIA_DIR, MEDIA_EXTS, PHOTOS_INBOX_DIR, VIDEO_EXTS

SHA256_INDEX_PATH = DATA_DIR / "photos" / "_sha256_index.json"
from ..exif_utils import extract_created_at_and_location, read_exif


def now_local_iso() -> str:
    return datetime.now().astimezone().isoformat(timespec="seconds")


def batch_folder_name(dt: datetime) -> str:
    return dt.strftime("%Y-%m-%d_%H%M")


def safe_name(s: str) -> str:
    s = s.strip()
    s = re.sub(r"\s+", "_", s)
    s = re.sub(r"[^A-Za-z0-9._-]+", "", s)
    s = s.strip("._-")
    return s or "file"


def unique_filename(prefix: str, original: str) -> str:
    base = Path(original).name
    stem = safe_name(Path(base).stem)
    ext = Path(base).suffix.lower() or ".bin"
    suffix = f"{os.getpid()}"
    return f"{prefix}_{stem}_{suffix}{ext}"


def is_image_file(p: Path) -> bool:
    return p.suffix.lower() in IMG_EXTS


def is_video_file(p: Path) -> bool:
    return p.suffix.lower() in VIDEO_EXTS


def is_live_photo_video_file(path: Path) -> bool:
    """Return True for the MOV companion generated by iPhone Live Photos.

    The reliable markers are the QuickTime metadata fields
    ``com.apple.quicktime.content.identifier`` and
    ``com.apple.quicktime.still-image-time``. We scan both the head and the tail
    because the QuickTime ``moov`` atom can appear at the end of the file.
    """
    if not path.is_file() or not is_video_file(path):
        return False
    try:
        size = path.stat().st_size
        if size <= 0:
            return False
        chunk = min(size, 8 * 1024 * 1024)
        with path.open("rb") as f:
            head = f.read(chunk)
            if size > chunk:
                f.seek(size - chunk)
                tail = f.read(chunk)
            else:
                tail = b""
        blob = (head + tail).lower()
        return (
            b"com.apple.quicktime.content.identifier" in blob
            or b"com.apple.quicktime.still-image-time" in blob
        )
    except Exception:
        return False


def is_media_file(p: Path) -> bool:
    return p.suffix.lower() in MEDIA_EXTS


def sidecar_path_for(img: Path) -> Path:
    try:
        rel = img.resolve().relative_to(MEDIA_DIR.resolve())
    except ValueError:
        return img.with_suffix(img.suffix + ".json")
    return DATA_DIR / f"{rel.as_posix()}.json"


def resolve_media_path(rel: str) -> Path:
    """Resolve a media path relative to MEDIA_DIR and prevent traversal."""
    rel = rel.lstrip("/\\")
    p = (MEDIA_DIR / rel).resolve()
    media_root = MEDIA_DIR.resolve()
    if not p.is_relative_to(media_root):
        raise ValueError("Path traversal")
    return p


def resolve_data_path(rel: str) -> Path:
    return resolve_media_path(rel)


def load_or_init_sidecar_for_image(img: Path) -> dict[str, Any]:
    sc_path = sidecar_path_for(img)
    if sc_path.exists():
        sc = load_sidecar(sc_path)
    else:
        sc = {}
    return ensure_sidecar_fields(sc)


def update_sidecar_fields(sc: dict[str, Any], people: list[str], tags: list[str], caption: str) -> dict[str, Any]:
    sc = ensure_sidecar_fields(sc)
    sc["people"] = people
    sc["tags"] = tags
    sc["caption"] = caption
    return sc


def bulk_toggle_sidecar_fields(
    sc: dict[str, Any],
    *,
    add_people: list[str],
    remove_people: list[str],
    add_tags: list[str],
    remove_tags: list[str],
) -> dict[str, Any]:
    sc = ensure_sidecar_fields(sc)

    people = [str(x) for x in (sc.get("people") or []) if x is not None and str(x).strip()]
    tags = [str(x) for x in (sc.get("tags") or []) if x is not None and str(x).strip()]

    def add_many(base: list[str], xs: list[str]) -> list[str]:
        out = list(base)
        for x in xs:
            if x not in out:
                out.append(x)
        return out

    def remove_many(base: list[str], xs: list[str]) -> list[str]:
        return [x for x in base if x not in xs]

    people = add_many(people, add_people)
    people = remove_many(people, remove_people)

    tags = add_many(tags, add_tags)
    tags = remove_many(tags, remove_tags)

    sc["people"] = people
    sc["tags"] = tags
    return sc


def load_sidecar(path: Path) -> dict[str, Any]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


def save_sidecar(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def load_sha256_index() -> dict[str, str]:
    """hash -> relative path (posix)"""
    try:
        if SHA256_INDEX_PATH.exists():
            data = json.loads(SHA256_INDEX_PATH.read_text(encoding="utf-8"))
            if isinstance(data, dict):
                return {str(k): str(v) for k, v in data.items()}
    except Exception:
        pass
    return {}


def save_sha256_index(idx: dict[str, str]) -> None:
    SHA256_INDEX_PATH.parent.mkdir(parents=True, exist_ok=True)
    SHA256_INDEX_PATH.write_text(json.dumps(idx, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def _quicktime_created_at(path: Path) -> str | None:
    """Read creation_time from an MP4/MOV without decoding the video."""
    import struct

    def read_boxes(data: bytes, end: int, wanted: set[str], start: int = 0) -> dict[str, tuple[int, int]]:
        found: dict[str, tuple[int, int]] = {}
        pos = start
        while pos + 8 <= end and len(found) < len(wanted):
            size = struct.unpack_from(">I", data, pos)[0]
            kind = data[pos + 4 : pos + 8]
            header = 8
            if size == 1 and pos + 16 <= end:
                size = struct.unpack_from(">Q", data, pos + 8)[0]
                header = 16
            elif size == 0:
                size = end - pos
            if size < header or pos + size > end:
                break
            name = kind.decode("latin1", errors="ignore")
            if name in wanted:
                found[name] = (pos + header, pos + size)
            pos += size
        return found

    try:
        with path.open("rb") as f:
            head = f.read(8 * 1024 * 1024)
    except Exception:
        return None
    if len(head) < 16:
        return None
    moov = read_boxes(head, len(head), {"moov"}).get("moov")
    if not moov:
        return None
    mvhd = read_boxes(head, moov[1], {"mvhd"}, moov[0]).get("mvhd")
    if not mvhd:
        return None
    body = head[mvhd[0] : mvhd[1]]
    if len(body) < 20:
        return None
    version = body[0]
    if version == 1 and len(body) >= 28:
        epoch = struct.unpack_from(">Q", body, 12)[0]
    else:
        epoch = struct.unpack_from(">I", body, 4)[0]
    if epoch <= 0:
        return None
    # QuickTime epoch is 1904-01-01 UTC.
    try:
        dt = datetime.fromtimestamp(epoch - 2082844800, tz=datetime.now().astimezone().tzinfo)
    except (OverflowError, OSError, ValueError):
        return None
    return dt.isoformat(timespec="seconds")


def build_sidecar_for_image(img: Path) -> dict[str, Any]:
    created_at = None
    created_src = None
    lat = lon = None
    if is_video_file(img):
        created_at = _quicktime_created_at(img)
        created_src = "quicktime" if created_at else None
    else:
        try:
            tags = read_exif(img)
            created_at, created_src, lat, lon = extract_created_at_and_location(tags)
        except Exception:
            pass

    sidecar: dict[str, Any] = {
        "people": [],
        "tags": [],
        "caption": "",
        "createdAt": created_at,
        "addedAt": now_local_iso(),
    }

    sidecar["createdAtSource"] = created_src or ("missing" if created_at is None else "exif")

    if lat is not None and lon is not None:
        sidecar["location"] = {"lat": lat, "lon": lon, "source": "exif_gps"}
    else:
        sidecar["location"] = None
        sidecar["locationSource"] = "missing"

    return sidecar


def ensure_sidecar_fields(sidecar: dict[str, Any]) -> dict[str, Any]:
    sidecar.setdefault("people", [])
    sidecar.setdefault("tags", [])
    sidecar.setdefault("caption", "")
    if not sidecar.get("addedAt"):
        sidecar["addedAt"] = now_local_iso()
    return sidecar
