from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Optional
import hashlib

from .config import DATA_DIR, IMG_EXTS, MEDIA_EXTS, PHOTOS_INBOX_DIR, VIDEO_EXTS

SHA256_INDEX_PATH = DATA_DIR / "photos" / "_sha256_index.json"
GALLERY_ORDER_PATH = DATA_DIR / "photos" / "_gallery_order.json"
GALLERY_PATHS_PATH = DATA_DIR / "photos" / "_gallery_paths.json"
from .exif_utils import extract_created_at_and_location, read_exif


def now_local_iso() -> str:
    return datetime.now().astimezone().isoformat(timespec="seconds")


def batch_folder_name(dt: datetime) -> str:
    return dt.strftime("%Y-%m-%d_%H%M")


def safe_name(s: str) -> str:
    s = s.strip()
    s = re.sub(r"\s+", "_", s)
    s = re.sub(r"[^A-Za-z0-9._-]+", "", s)
    s = s.strip("._-")
    return s or "file"


def unique_filename(prefix: str, original: str) -> str:
    base = Path(original).name
    stem = safe_name(Path(base).stem)
    ext = Path(base).suffix.lower() or ".bin"
    suffix = f"{os.getpid()}"
    return f"{prefix}_{stem}_{suffix}{ext}"


def is_image_file(p: Path) -> bool:
    return p.suffix.lower() in IMG_EXTS


def is_video_file(p: Path) -> bool:
    return p.suffix.lower() in VIDEO_EXTS


def is_live_photo_video_file(path: Path) -> bool:
    """Return True for the MOV companion generated by iPhone Live Photos.

    The reliable markers are the QuickTime metadata fields
    ``com.apple.quicktime.content.identifier`` and
    ``com.apple.quicktime.still-image-time``. We scan both the head and the tail
    because the QuickTime ``moov`` atom can appear at the end of the file.
    """
    if not path.is_file() or not is_video_file(path):
        return False
    try:
        size = path.stat().st_size
        if size <= 0:
            return False
        chunk = min(size, 8 * 1024 * 1024)
        with path.open("rb") as f:
            head = f.read(chunk)
            if size > chunk:
                f.seek(size - chunk)
                tail = f.read(chunk)
            else:
                tail = b""
        blob = (head + tail).lower()
        return (
            b"com.apple.quicktime.content.identifier" in blob
            or b"com.apple.quicktime.still-image-time" in blob
        )
    except Exception:
        return False


def is_media_file(p: Path) -> bool:
    return p.suffix.lower() in MEDIA_EXTS


def sidecar_path_for(img: Path) -> Path:
    return img.with_suffix(img.suffix + ".json")


def resolve_data_path(rel: str) -> Path:
    """Resolve a path relative to DATA_DIR and prevent traversal."""
    rel = rel.lstrip("/\\")
    p = (DATA_DIR / rel).resolve()
    data_root = DATA_DIR.resolve()
    if not str(p).startswith(str(data_root)):
        raise ValueError("Path traversal")
    return p


def load_or_init_sidecar_for_image(img: Path) -> dict[str, Any]:
    sc_path = sidecar_path_for(img)
    if sc_path.exists():
        sc = load_sidecar(sc_path)
    else:
        sc = {}
    return ensure_sidecar_fields(sc)


def update_sidecar_fields(sc: dict[str, Any], people: list[str], tags: list[str], caption: str) -> dict[str, Any]:
    sc = ensure_sidecar_fields(sc)
    sc["people"] = people
    sc["tags"] = tags
    sc["caption"] = caption
    return sc


def bulk_toggle_sidecar_fields(
    sc: dict[str, Any],
    *,
    add_people: list[str],
    remove_people: list[str],
    add_tags: list[str],
    remove_tags: list[str],
) -> dict[str, Any]:
    sc = ensure_sidecar_fields(sc)

    people = [str(x) for x in (sc.get("people") or []) if x is not None and str(x).strip()]
    tags = [str(x) for x in (sc.get("tags") or []) if x is not None and str(x).strip()]

    def add_many(base: list[str], xs: list[str]) -> list[str]:
        out = list(base)
        for x in xs:
            if x not in out:
                out.append(x)
        return out

    def remove_many(base: list[str], xs: list[str]) -> list[str]:
        return [x for x in base if x not in xs]

    people = add_many(people, add_people)
    people = remove_many(people, remove_people)

    tags = add_many(tags, add_tags)
    tags = remove_many(tags, remove_tags)

    sc["people"] = people
    sc["tags"] = tags
    return sc


def load_sidecar(path: Path) -> dict[str, Any]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


def save_sidecar(path: Path, data: dict[str, Any]) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def load_sha256_index() -> dict[str, str]:
    """hash -> relative path (posix)"""
    try:
        if SHA256_INDEX_PATH.exists():
            data = json.loads(SHA256_INDEX_PATH.read_text(encoding="utf-8"))
            if isinstance(data, dict):
                return {str(k): str(v) for k, v in data.items()}
    except Exception:
        pass
    return {}


def save_sha256_index(idx: dict[str, str]) -> None:
    SHA256_INDEX_PATH.parent.mkdir(parents=True, exist_ok=True)
    SHA256_INDEX_PATH.write_text(json.dumps(idx, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def iter_inbox_images():
    """Yield inbox images as they are found. Does not sort or buffer the whole tree."""
    PHOTOS_INBOX_DIR.mkdir(parents=True, exist_ok=True)
    for p in PHOTOS_INBOX_DIR.rglob("*"):
        if not p.is_file():
            continue
        if not is_media_file(p):
            continue
        if "thumbs" in p.parts:
            continue
        if is_live_photo_video_file(p):
            continue
        yield p


def _sidecar_created_at(img: Path) -> str | None:
    sc_path = sidecar_path_for(img)
    if not sc_path.exists():
        return None
    try:
        data = json.loads(sc_path.read_text(encoding="utf-8"))
    except Exception:
        return None
    if not isinstance(data, dict):
        return None
    created = data.get("createdAt")
    return str(created) if created else None


_ranked_rels: list[str] | None = None
_ranked_index: dict[str, int] | None = None


def invalidate_gallery_rank() -> None:
    global _ranked_rels, _ranked_index
    _ranked_rels = None
    _ranked_index = None


def ranked_gallery_rels() -> list[str]:
    """Newest-first paths from the date cache. Built once, reused by every page."""
    global _ranked_rels, _ranked_index
    if _ranked_rels is None:
        order = load_gallery_order()
        _ranked_rels = sorted(order, key=lambda rel: order_sort_key(rel, order.get(rel)))
        _ranked_index = {rel: i for i, rel in enumerate(_ranked_rels)}
    return _ranked_rels


def _page_from_order(limit: int, before_path: str | None) -> tuple[list[Path], bool] | None:
    ranked = ranked_gallery_rels()
    if not ranked:
        return None
    if before_path:
        index = _ranked_index or {}
        start = index.get(before_path)
        start = 0 if start is None else start + 1
    else:
        start = 0
    page: list[Path] = []
    for rel in ranked[start:]:
        try:
            img = resolve_data_path(rel)
        except ValueError:
            continue
        if img.is_file():
            page.append(img)
        if len(page) >= limit:
            break
    return page, start + len(page) < len(ranked)


def newest_inbox_images(limit: int, before_path: str | None = None) -> tuple[list[Path], bool]:
    """Return the next dated photos after ``before_path`` in newest-first order.

    Uses the date cache when it exists. Otherwise only batch folders old enough
    to contain the next page are opened.
    """
    limit = max(1, limit)
    cached = _page_from_order(limit, before_path)
    if cached is not None:
        return cached
    cursor_created = ""
    if before_path:
        try:
            cursor_created = _sidecar_created_at(resolve_data_path(before_path)) or ""
        except ValueError:
            cursor_created = ""
    cursor_day = cursor_created[:10]
    cursor_key = order_sort_key(before_path, cursor_created) if before_path else None

    PHOTOS_INBOX_DIR.mkdir(parents=True, exist_ok=True)
    folders = [p for p in PHOTOS_INBOX_DIR.iterdir() if p.is_dir() and not p.name.startswith("_")]
    loose = [p for p in PHOTOS_INBOX_DIR.iterdir() if p.is_file() and is_media_file(p)]
    folders.sort(key=lambda p: p.name, reverse=True)
    # Loose files have no batch date, so read them before assuming the page is complete.
    folders.append(PHOTOS_INBOX_DIR)

    found: list[tuple[str, Path]] = []
    scanned_all = True
    for folder in folders:
        if cursor_day and folder != PHOTOS_INBOX_DIR and folder.name[:10] > cursor_day:
            continue
        children = loose if folder == PHOTOS_INBOX_DIR else folder.rglob("*")
        for img in children:
            if not img.is_file() or not is_media_file(img) or "thumbs" in img.parts:
                continue
            created = _sidecar_created_at(img)
            rel = img.relative_to(DATA_DIR).as_posix()
            if cursor_key is not None and order_sort_key(rel, created) <= cursor_key:
                continue
            found.append((created or "", img))
        if len(found) >= limit and folder != PHOTOS_INBOX_DIR and folder.name[:10] < cursor_day:
            scanned_all = False
            break

    found.sort(key=lambda pair: order_sort_key(pair[1].as_posix(), pair[0]))
    page = [img for _, img in found[:limit]]
    return page, not scanned_all or len(found) > limit


def list_inbox_images() -> list[Path]:
    PHOTOS_INBOX_DIR.mkdir(parents=True, exist_ok=True)

    files: list[Path] = []
    for p in PHOTOS_INBOX_DIR.rglob("*"):
        if not p.is_file():
            continue
        if not is_media_file(p):
            continue
        # Ignore generated thumbnails directory
        if "thumbs" in p.parts:
            continue
        if is_live_photo_video_file(p):
            continue
        files.append(p)

    files.sort()
    return files


def load_gallery_paths() -> list[str]:
    try:
        if GALLERY_PATHS_PATH.exists():
            data = json.loads(GALLERY_PATHS_PATH.read_text(encoding="utf-8"))
            if isinstance(data, list):
                return [str(x) for x in data]
    except Exception:
        pass
    return []


def save_gallery_paths(rels: list[str]) -> None:
    GALLERY_PATHS_PATH.parent.mkdir(parents=True, exist_ok=True)
    GALLERY_PATHS_PATH.write_text(json.dumps(rels, ensure_ascii=False) + "\n", encoding="utf-8")


def load_gallery_order() -> dict[str, str | None]:
    """rel path -> createdAt from the last full gallery pass. None means missing."""
    try:
        if GALLERY_ORDER_PATH.exists():
            data = json.loads(GALLERY_ORDER_PATH.read_text(encoding="utf-8"))
            if isinstance(data, dict):
                return {str(k): (None if v is None else str(v)) for k, v in data.items()}
    except Exception:
        pass
    return {}


def save_gallery_order(order: dict[str, str | None]) -> None:
    GALLERY_ORDER_PATH.parent.mkdir(parents=True, exist_ok=True)
    GALLERY_ORDER_PATH.write_text(json.dumps(order, ensure_ascii=False) + "\n", encoding="utf-8")
    invalidate_gallery_rank()


def remember_gallery_items(rels_with_created: list[tuple[str, str | None]]) -> None:
    """Add uploaded photos to the paged gallery cache without a full inbox scan.

    The grid reads ``_gallery_order.json`` / ``_gallery_paths.json``. Uploads that
    are not recorded there never appear, even though the files are on disk.
    """
    if not rels_with_created:
        return
    order = load_gallery_order()
    paths = load_gallery_paths()
    known = set(paths)
    changed = False
    for rel, created in rels_with_created:
        rel = rel.replace("\\", "/")
        if rel not in order or order.get(rel) != created:
            order[rel] = created
            changed = True
        if rel not in known:
            paths.append(rel)
            known.add(rel)
            changed = True
    if not changed:
        return
    save_gallery_order(order)
    save_gallery_paths(paths)


def forget_gallery_items(rels: list[str]) -> None:
    """Drop trashed photos from the paged gallery cache."""
    if not rels:
        return
    drop = {rel.replace("\\", "/") for rel in rels}
    order = load_gallery_order()
    paths = load_gallery_paths()
    new_order = {rel: created for rel, created in order.items() if rel not in drop}
    new_paths = [rel for rel in paths if rel not in drop]
    if len(new_order) != len(order):
        save_gallery_order(new_order)
    if len(new_paths) != len(paths):
        save_gallery_paths(new_paths)


_gallery_disk_synced = False


_BATCH_FOLDER = re.compile(r"^\d{4}-\d{2}-\d{2}_\d{4}$")


def gallery_cache_watermark() -> str:
    """Newest batch-folder name already present in the gallery cache."""
    mark = ""
    for rel in load_gallery_paths():
        parts = rel.replace("\\", "/").split("/")
        if "inbox" not in parts:
            continue
        idx = parts.index("inbox") + 1
        if idx >= len(parts) - 1:
            continue
        folder = parts[idx]
        if _BATCH_FOLDER.match(folder) and folder > mark:
            mark = folder
    return mark


def sync_missing_gallery_items() -> int:
    """Index inbox images dropped on disk outside the upload endpoint.

    Only batch folders newer than the cache watermark are opened. A full inbox
    walk of ~10k photos was adding several seconds to every gallery page.
    """
    order = load_gallery_order()
    if not order and not GALLERY_PATHS_PATH.exists():
        return 0
    known = set(order) | set(load_gallery_paths())
    watermark = gallery_cache_watermark()
    missing: list[tuple[str, str | None]] = []

    PHOTOS_INBOX_DIR.mkdir(parents=True, exist_ok=True)
    folders = [p for p in PHOTOS_INBOX_DIR.iterdir() if p.is_dir() and not p.name.startswith("_")]
    for folder in folders:
        # "<" not "<=": the newest cached batch can still receive more files.
        if watermark and folder.name < watermark:
            continue
        for img in folder.rglob("*"):
            if not img.is_file() or not is_media_file(img) or "thumbs" in img.parts:
                continue
            if is_live_photo_video_file(img):
                continue
            rel = img.relative_to(DATA_DIR).as_posix()
            if rel in known:
                continue
            missing.append((rel, _sidecar_created_at(img)))

    for img in PHOTOS_INBOX_DIR.iterdir():
        if not img.is_file() or not is_media_file(img):
            continue
        if is_live_photo_video_file(img):
            continue
        rel = img.relative_to(DATA_DIR).as_posix()
        if rel in known:
            continue
        missing.append((rel, _sidecar_created_at(img)))

    if missing:
        remember_gallery_items(missing)
    return len(missing)


def sync_missing_gallery_items_once() -> int:
    """Run the disk catch-up at most once per process.

    Uploads call ``remember_gallery_items`` themselves, so later pages must not
    stat the inbox again. Warm the rank first so a no-op sync does not throw it away.
    """
    global _gallery_disk_synced
    if _gallery_disk_synced:
        return 0
    ranked_gallery_rels()
    added = sync_missing_gallery_items()
    if added:
        invalidate_gallery_rank()
    _gallery_disk_synced = True
    return added


def order_sort_key(rel: str, created_at: str | None):
    """Same order as sort_gallery_items: dated photos first (newest), missing last."""
    if not created_at:
        return (1, 0.0, rel)
    dt = parse_isoish(created_at)
    if dt is None:
        return (1, 0.0, rel)
    if dt.tzinfo is None:
        local_tz = datetime.now().astimezone().tzinfo
        if local_tz is not None:
            dt = dt.replace(tzinfo=local_tz)
    return (0, -dt.timestamp(), rel)


def parse_isoish(s: str) -> Optional[datetime]:
    try:
        return datetime.fromisoformat(s)
    except Exception:
        return None


def get_created_at_for_sort(sidecar: dict[str, Any], img: Path) -> tuple[bool, Optional[float], Optional[str]]:
    """Return (missing, timestampSeconds, createdAtStr)."""
    created_at = sidecar.get("createdAt")
    created_src = sidecar.get("createdAtSource")

    if not created_at:
        # if no createdAt, treat as missing and push to end.
        # only fallback to mtime for items without sidecar at all.
        if not sidecar:
            created_at = datetime.fromtimestamp(img.stat().st_mtime).astimezone().isoformat(timespec="seconds")
            dt = parse_isoish(created_at)
            return (False, dt.timestamp() if dt else None, created_at)
        return (True, None, None)

    dt = parse_isoish(str(created_at))
    if dt is None:
        return (True, None, None)

    if dt.tzinfo is None:
        local_tz = datetime.now().astimezone().tzinfo
        if local_tz is not None:
            dt = dt.replace(tzinfo=local_tz)

    return (False, dt.timestamp(), str(created_at))


def _quicktime_created_at(path: Path) -> str | None:
    """Read creation_time from an MP4/MOV without decoding the video."""
    import struct

    def read_boxes(data: bytes, end: int, wanted: set[str], start: int = 0) -> dict[str, tuple[int, int]]:
        found: dict[str, tuple[int, int]] = {}
        pos = start
        while pos + 8 <= end and len(found) < len(wanted):
            size = struct.unpack_from(">I", data, pos)[0]
            kind = data[pos + 4 : pos + 8]
            header = 8
            if size == 1 and pos + 16 <= end:
                size = struct.unpack_from(">Q", data, pos + 8)[0]
                header = 16
            elif size == 0:
                size = end - pos
            if size < header or pos + size > end:
                break
            name = kind.decode("latin1", errors="ignore")
            if name in wanted:
                found[name] = (pos + header, pos + size)
            pos += size
        return found

    try:
        with path.open("rb") as f:
            head = f.read(8 * 1024 * 1024)
    except Exception:
        return None
    if len(head) < 16:
        return None
    moov = read_boxes(head, len(head), {"moov"}).get("moov")
    if not moov:
        return None
    mvhd = read_boxes(head, moov[1], {"mvhd"}, moov[0]).get("mvhd")
    if not mvhd:
        return None
    body = head[mvhd[0] : mvhd[1]]
    if len(body) < 20:
        return None
    version = body[0]
    if version == 1 and len(body) >= 28:
        epoch = struct.unpack_from(">Q", body, 12)[0]
    else:
        epoch = struct.unpack_from(">I", body, 4)[0]
    if epoch <= 0:
        return None
    # QuickTime epoch is 1904-01-01 UTC.
    try:
        dt = datetime.fromtimestamp(epoch - 2082844800, tz=datetime.now().astimezone().tzinfo)
    except (OverflowError, OSError, ValueError):
        return None
    return dt.isoformat(timespec="seconds")


def build_sidecar_for_image(img: Path) -> dict[str, Any]:
    created_at = None
    created_src = None
    lat = lon = None
    if is_video_file(img):
        created_at = _quicktime_created_at(img)
        created_src = "quicktime" if created_at else None
    else:
        try:
            tags = read_exif(img)
            created_at, created_src, lat, lon = extract_created_at_and_location(tags)
        except Exception:
            pass

    sidecar: dict[str, Any] = {
        "people": [],
        "tags": [],
        "caption": "",
        "createdAt": created_at,
        "addedAt": now_local_iso(),
    }

    sidecar["createdAtSource"] = created_src or ("missing" if created_at is None else "exif")

    if lat is not None and lon is not None:
        sidecar["location"] = {"lat": lat, "lon": lon, "source": "exif_gps"}
    else:
        sidecar["location"] = None
        sidecar["locationSource"] = "missing"

    return sidecar


def ensure_sidecar_fields(sidecar: dict[str, Any]) -> dict[str, Any]:
    sidecar.setdefault("people", [])
    sidecar.setdefault("tags", [])
    sidecar.setdefault("caption", "")
    if not sidecar.get("addedAt"):
        sidecar["addedAt"] = now_local_iso()
    return sidecar


def sort_gallery_items(items: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Sort gallery items: non-missing first, then createdAt desc. Missing last."""

    local_tz = datetime.now().astimezone().tzinfo

    def sort_key(it: dict[str, Any]):
        is_missing = 1 if it.get("missing") else 0
        dt = parse_isoish(str(it.get("createdAt") or ""))
        if dt is None:
            ts = float("-inf")
        else:
            if dt.tzinfo is None and local_tz is not None:
                dt = dt.replace(tzinfo=local_tz)
            ts = dt.timestamp()
        return (is_missing, -ts)

    items.sort(key=sort_key)
    return items
